AWSTemplateFormatVersion: 2010-09-09
Description: ---
Metadata: 

Parameters: 

Mappings: 

Conditions: 

Resources: 
VPCTercerProyecto:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: 172.50.0.0/16
    EnableDnsSupport: true
    Tags:
      - Key: name
        Value: VPCPROYECTO
Outputs: